server:
  port: ${PORT:8072}
hostname: ${HOSTNAME:localhost:8072}
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka
spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/v1/chat/**
          filters:
  #          - RewritePath=/api/v1/chat/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
  #          - RewritePath=/api/v1/auth/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: remote-code-execution-client-service
          uri: lb://remote-code-execution-client-service
          predicates:
            - Path=/codeExecutor/**
          filters:
            - RewritePath=/codeExecutor/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: remote-code-execution-server-service
          uri: lb://remote-code-execution-server-service
          predicates:
            - Path=/codeExecutor/**
          filters:
            - RewritePath=/codeExecutor/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: files-management-service
          uri: lb://files-management-service
          predicates:
            - Path=/files-management/**
          filters:
            - RewritePath=/files-management/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: users-group-service
          uri: lb://users-group-service
          predicates:
            - Path=/users-group/**
          filters:
            - RewritePath=/users-group/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/post/**
          filters:
            - RewritePath=/post/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/project/**
          filters:
            - RewritePath=/project/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

  # Disable accessing services using service name (i.e. students-service).
  # They should be only accessed through the path defined below.
zuul:
  # Exclude authorization from sensitive headers
  sensitive-headers: Cookie,Set-Cookie
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  ignored-services: '*'
  # Map paths to services
  routes:
    # Map path to chat service
    chat-service:
      path: /api/v1/chat/**
      service-id: CHAT-SERVICE
      strip-prefix: false
    # Map path to auth service
    auth-service:
      path: /api/v1/auth/**
      service-id: AUTH-SERVICE
      strip-prefix: false
    # Map path to code execution server service
    remote-code-execution-server-service:
      path: /api/v1/codeExecutor/**
      service-id: REMOTE-CODE-EXECUTION-CLIENT-SERVICE
      strip-prefix: false
    # Map path to code execution client service
    remote-code-execution-client-service:
      path: /api/v1/codeExecutor/**
      service-id: REMOTE-CODE-EXECUTION-CLIENT-SERVICE
      strip-prefix: false
    # Map path to code execution files management service
    files-management-service:
      path: /api/v1/files/**
      service-id: FILES-MANAGEMENT-SERVICE
      strip-prefix: false
    # Map path to code execution user group service
    user-group-service:
      path: /api/v1/groups/**
      service-id: USER-GROUP-SERVICE
      strip-prefix: false
    # Map path to code execution user group service
    post-service:
      path: /api/v1/post/**
      service-id: POST-SERVICE
      strip-prefix: false
    # Map path to code execution user group service
    project-service:
      path: /api/v1/project/**
      service-id: PROJECT-SERVICE
      strip-prefix: false

ribbon:
  ReadTimeout: 60000

jwt:
  header: Authorization
  secret: ${JWT_SECRET:BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY}
  expiration: 86400