management:
  endpoints:
    web:
      exposure:
        include: info,refresh,keepalive,health
spring:
  application:
    name: gateway-service

logging:
  level:
   org:
    springframework:
     cloud:
      kubernetes: DEBUG