hostname: localhost:4200
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:config-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/v1/chat/**
          filters:
            - RewritePath=/api/v1/chat/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

management:
  endpoints:
    web:
      exposure:
        include: '*'